<a href="https://colab.research.google.com/github/FREDDYNG1/Repositorio-para-suo-de-programacion/blob/main/Ejercicios_para_Aprender_con_lista_y_condicionales.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Ejemplo de condiciones y listas en Python

# Definir una lista de números
numeros = [5, 10, 15, 20, 25]

# Iterar sobre cada número en la lista
for numero in numeros:
    # Comprobar si el número es divisible por 3 y 5
    if numero % 3 == 0 and numero % 5 == 0:
        print(f"{numero} es divisible por 3 y 5")
    # Comprobar si el número es divisible solo por 3
    elif numero % 3 == 0:
        print(f"{numero} es divisible por 3")
    # Comprobar si el número es divisible solo por 5
    elif numero % 5 == 0:
        print(f"{numero} es divisible por 5")
    # Si no se cumple ninguna de las condiciones anteriores
    else:
        print(f"{numero} no es divisible por 3 ni por 5")


5 es divisible por 5
10 es divisible por 5
15 es divisible por 3 y 5
20 es divisible por 5
25 es divisible por 5


In [ ]:
#arreglos unidimensionales # Vector
import numpy
arreglo = numpy.array(([1, 2, 3, 4, 6,5, 7]))
print(arreglo[6])

7


In [ ]:
#arreglos bidimensionales # matriz
import numpy
matriz = numpy.array([[3, 2, 4, 10],[15, 11, 7, 3]])
for f in range (1): #
    for c in range (2):# toma lo que esta dentro de esa posicion no la ultima
      print(matriz[f , c])


3
2


In [ ]:
import numpy
matriz = numpy.array([[0, 1, 2],[3, 4, 5]])
for f in range (2):
    for c in range (3):
      print(matriz[f , c])
print("")
print(matriz[1,1])

0
1
2
3
4
5

4


In [ ]:
import numpy as np

matriz = np.zeros((3, 3), dtype=np.int)
print(matriz)


[[0 0 0]
 [0 0 0]
 [0 0 0]]


<ipython-input-76-fa03272f9e19>:3: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  matriz = np.zeros((3, 3), dtype=np.int)


In [ ]:
import numpy as np

arreglo = np.random.randint(0, 101, size=(3, 3))
print(arreglo)


[[27 67 34]
 [72 85 91]
 [39 10 32]]


In [ ]:
# CALCULADORA CON FUNCIONES def()


def suma(a, b):
    return a + b

def resta(a, b):
    return a - b

def multiplicacion(a, b):
    return a * b

def dividir(a, b):
    return a / b

def menu():
    while True:
        print("1. sumar")
        print("2. restar")
        print("3. multiplicacion")
        print("4. dividir")
        print("5. cancelar")

        opcion = int(input("Seleccione una opción ): "))

        if opcion == 1:
            a = int(input("Ingrese el primer número: "))
            b = int(input("Ingrese el segundo número: "))
            result = suma(a, b)
            print("El resultado de la suma es:", result)

        elif opcion == 2:
            a = int(input("Ingrese el primer número: "))
            b = int(input("Ingrese el segundo número: "))
            result = resta(a, b)
            print("El resultado de la resta es:", result)

        elif opcion == 3:
            a = int(input("Ingrese el primer número: "))
            b = int(input("Ingrese el segundo número: "))
            result = multiplicacion(a, b)
            print("El resultado de la multiplicación es:", result)

        elif opcion == 4:
            a = int(input("Ingrese el primer número: "))
            b = int(input("Ingrese el segundo número: "))
            result = dividir(a, b)
            print("El resultado de la división es:", result)

        elif opcion == 5:
            print("Ha cancelado la operación.")
            break

        else:
            print("Opción inválida. Por favor, seleccione una opción válida.")

def main():
    menu()

main()









1. sumar
2. restar
3. multiplicacion
4. dividir
5. cancelar


KeyboardInterrupt: ignored

In [ ]:
personas = []

def GUARDAR():
    rut = input("Ingrese RUT: ")
    nombre = input("Ingrese NOMBRE: ")
    edad = int(input("Ingrese EDAD: "))
    pais_de_nacimiento = input("Ingrese PAÍS DE NACIMIENTO: ")
    ciudad_de_nacimiento = input("Ingrese CIUDAD DE NACIMIENTO: ")

    if validar_rut(rut):
        persona = {
            "rut": rut,
            "nombre": nombre,
            "edad": edad,
            "pais_de_nacimiento": pais_de_nacimiento,
            "ciudad_de_nacimiento": ciudad_de_nacimiento
        }
        personas.append(persona)
        print("Persona guardada exitosamente.")
    else:
        print("El RUT ingresado no es válido.")

def validar_rut(rut):
    rut = rut.replace(".", "").replace("-", "")
    if len(rut) != 9 or not rut[:-1].isdigit():
        return False
    multiplicadores = [2, 3, 4, 5, 6, 7, 2, 3]
    total = sum(int(digito) * multiplicador for digito, multiplicador in zip(rut[:-1][::-1], multiplicadores))
    resto = total % 11
    digito_verificador = str(11 - resto)
    if digito_verificador == "11":
        digito_verificador = "0"
    elif digito_verificador == "10":
        digito_verificador = "K"
    return rut[-1].upper() == digito_verificador

def buscar():
    rut = input("Ingrese RUT de la persona que desea buscar: ")
    found = False
    for persona in personas:
        if persona["rut"] == rut:
            print("Persona encontrada:")
            print("RUT:", persona["rut"])
            print("Nombre:", persona["nombre"])
            print("Edad:", persona["edad"])
            print("País de Nacimiento:", persona["pais_de_nacimiento"])
            print("Ciudad de Nacimiento:", persona["ciudad_de_nacimiento"])
            found = True
            break
    if not found:
        print("Persona no encontrada.")

def imprimir_certificados():
    certificado_nacimiento = input("Ingrese el nombre del certificado de nacimiento: ")
    certificado_de_matrimonio = input("Ingrese el certificado de matrimonio: ")
    # Aquí puedes implementar la lógica para imprimir los certificados correspondientes
    # utilizando los nombres proporcionados

def eliminar():
    rut = input("Ingrese el RUT de la persona que desea eliminar: ")
    removed = False
    for persona in personas:
        if persona["rut"] == rut:
            personas.remove(persona)
            removed = True
            print("Persona eliminada exitosamente.")
            break
    if not removed:
        print("Persona no encontrada.")

def main():
    while True:
        print("-----MENÚ-----")
        print("1. GUARDAR")
        print("2. BUSCAR")
        print("3. IMPRIMIR CERTIFICADOS")
        print("4. ELIMINAR")
        print("5. SALIR")

        opcion = int(input("Ingrese la opción que desea: "))

        if opcion == 1:
            GUARDAR()
        elif opcion == 2:
            buscar()
        elif opcion == 3:
            imprimir_certificados()
        elif opcion == 4:
            eliminar()
        elif opcion == 5:
            print("Hasta luego")
            break
        else:
            print("Opción inválida. Por favor, ingrese nuevamente.")

if __name__ == "__main__":
    main()


In [ ]:
# CASO PRUEBA
def grabar():
    rut = input("Ingrese RUT: ")
    nombre = input("Ingrese NOMBRE: ")
    edad = int(input("Ingrese EDAD: "))
    pais_de_nacimiento = input("Ingrese PAÍS DE NACIMIENTO: ")
    ciudad_de_nacimiento = input("Ingrese CIUDAD DE NACIMIENTO: ")

    if validar_rut(rut) and len(nombre) >= 8 and edad >= 0:
        print("Datos guardados con éxito")
    else:
        print("Error en los datos ingresados. Por favor, inténtelo de nuevo")


def buscar():
    rut = input("Ingrese RUT de la persona que desea buscar: ")
    # Aquí puedes implementar la lógica para buscar el RUT en tu sistema
    # y realizar las acciones correspondientes


def imprimir_certificados():
    certificado_nacimiento = input("Ingrese el nombre del certificado de nacimiento: ")
    certificado_de_matrimonio = input("Ingrese el certificado de matrimonio: ")
    # Aquí puedes implementar la lógica para imprimir los certificados
    # correspondientes utilizando los nombres proporcionados


def eliminar():
    rut = input("Ingrese el RUT que desea eliminar: ")
    # Aquí puedes implementar la lógica para eliminar la persona con el
    # RUT proporcionado de tu sistema


def main():
    while True:
        print("-----MENÚ-----")
        print("1. GRABAR")
        print("2. BUSCAR")
        print("3. IMPRIMIR CERTIFICADOS")
        print("4. ELIMINAR")
        print("5. SALIR")

        opcion = int(input("Ingrese la opción que desea: "))

        if opcion == 1:
            grabar()
        elif opcion == 2:
            buscar()
        elif opcion == 3:
            imprimir_certificados()
        elif opcion == 4:
            eliminar()
        elif opcion == 5:
            print("Hasta luego")
            break
        else:
            print("Opción inválida. Por favor, ingrese nuevamente.")


if __name__ == "__main__":
    main()


In [ ]:
resultado1 = 2**8
resultado2 = 5+8
print("el resultado de la potencia es: ", resultado1 ,  "\n y el resultado de la suma es :" , resultado2 )

el resultado de la potencia es:  256 
 y el resultado de la suma es : 13


In [ ]:
# ano comun o bisieto
year = int(input("ingresa un ano: "))

if year < 1582:
  print("no dentro del periodo del calendario gregoriano")
else:
    if year  %  4 != 0:
     print("ano comun")

    elif year % 100 != 0:
     print("ano bisieto")

    elif year % 400 != 0:
       print("ano comun")

    else:
        print("ano bisieto")


ingresa un ano: 26617
ano comun


In [ ]:
personas = []

def GUARDAR():
    rut = input("Ingrese RUT: ")
    nombre = input("Ingrese NOMBRE: ")
    edad = int(input("Ingrese EDAD: "))
    pais_de_nacimiento = input("Ingrese PAÍS DE NACIMIENTO: ")
    ciudad_de_nacimiento = input("Ingrese CIUDAD DE NACIMIENTO: ")

    if validar_rut(rut):
        persona = {
            "rut": rut,
            "nombre": nombre,
            "edad": edad,
            "pais_de_nacimiento": pais_de_nacimiento,
            "ciudad_de_nacimiento": ciudad_de_nacimiento
        }
        personas.append(persona)
        print("Persona guardada exitosamente.")
    else:
        print("El RUT ingresado no es válido.")

def validar_rut(rut):
    rut = rut.replace(".", "").replace("-", "")
    if len(rut) != 9 or not rut[:-1].isdigit():
        return False
    multiplicadores = [2, 3, 4, 5, 6, 7, 2, 3]
    total = sum(int(digito) * multiplicador for digito, multiplicador in zip(rut[:-1][::-1], multiplicadores))
    resto = total % 11
    digito_verificador = str(11 - resto)
    if digito_verificador == "11":
        digito_verificador = "0"
    elif digito_verificador == "10":
        digito_verificador = "K"
    return rut[-1].upper() == digito_verificador

def buscar():
    rut = input("Ingrese RUT de la persona que desea buscar: ")
    found = False
    for persona in personas:
        if persona["rut"] == rut:
            print("Persona encontrada:")
            print("RUT:", persona["rut"])
            print("Nombre:", persona["nombre"])
            print("Edad:", persona["edad"])
            print("País de Nacimiento:", persona["pais_de_nacimiento"])
            print("Ciudad de Nacimiento:", persona["ciudad_de_nacimiento"])
            found = True
            break
    if not found:
        print("Persona no encontrada.")

def imprimir_certificados():
    certificado_nacimiento = input("Ingrese el nombre del certificado de nacimiento: ")
    certificado_de_matrimonio = input("Ingrese el certificado de matrimonio: ")


def eliminar():
    rut = input("Ingrese el RUT de la persona que desea eliminar: ")
    removed = False
    for persona in personas:
        if persona["rut"] == rut:
            personas.remove(persona)
            removed = True
            print("Persona eliminada exitosamente.")
            break
    if not removed:
        print("Persona no encontrada.")

def main():
    while True:
        print("-----MENÚ-----")
        print("1. GUARDAR")
        print("2. BUSCAR")
        print("3. IMPRIMIR CERTIFICADOS")
        print("4. ELIMINAR")
        print("5. SALIR")

        opcion = int(input("Ingrese la opción que desea: "))

        if opcion == 1:
            GUARDAR()
        elif opcion == 2:
            buscar()
        elif opcion == 3:
            imprimir_certificados()
        elif opcion == 4:
            eliminar()
        elif opcion == 5:
            print("Hasta luego")
            break
        else:
            print("Opción inválida. Por favor, ingrese nuevamente.")

if __name__ == "__main__":
    main()